@startuml
left to right direction
skinparam packagestyle rect
actor 所有用户
actor 登录的用户
actor 系统管理员


rectangle 查书{
 所有用户 -- (图书外借情况)
 所有用户 -- (位置--楼层，阅览室)
 所有用户 -- (索书号--具体的书架定位)
 所有用户 -- (虚拟书架--查看该书附近的图书)
 所有用户 -- (豆瓣信息--评分，简介)
 所有用户 -- (借阅排名)

}

rectangle 个人信息{
 登录的用户--(个人的外借信息)
 登录的用户--(历史借阅信息)
 登录的用户--(图书预约服务)
}

rectangle 机器人控制{
 系统管理员 -- (基础运动控制)
 系统管理员 -- (书架信息录入)
 系统管理员 -- (自动化任务管理)
}
@enduml